language: generic
branches:
  only:
    - master
services:
  - docker
sudo: required
deploy:
  provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
notifications:
  webhooks:
    urls:
      - secure: "JBNbumIm6QiQPHoyXWAUzgBgTICwoNGi5/aPPOy7P6OsxmAKriPfItKXPKKMXklEXdtwgbJgU2xu5Y0re/K4R8iZNo0XgCn+Z85BT+Gbm9c5lpae7iyVXITq0ewVVjDSabvkEYAgSIs+2VWGImQUUziGsYYFxHSvkpoCN65bLtM3319/zoYf9FfTivUVs6R3eusQxJXIibXYp1Gm57G42m7B6xS0FbTMVoKWAzKZ5jjuA3XB9HIHhnzH6xAdkLB0de4vCwt1SQwZboLL8hOfSV730McmqnmupeY6zJLWRCV2xeylpR1+M0g+jGralSUOV8QAMAi8fEzBwS3rcd7b4iefaW75yncvwo0xCRxlLicSCETbZeaipkB/EZne2EbeG0/rTbxbXrJgXNZXioymfQx2iblkUIGLe9aJ4+BIYUFkF/9fhEeXycboGQgScBJyEWdlsK4YfREfdu/ymPeRvNDj2DjniyFeMAcNn/dDDAXzPbz21NKpuAkHnBnOAnDVRJq7Tw5ZNsCfg6RaiAEtKbxedbgoZ5IiB491kyKZSLJL1HHD4Fq5Bxm47LX52uWUguoqSmbjj6b/G1CfdpN6SUXJSAAnQbymsFRVGpFsVKa2iiZu3pa7qN/ivbqDpnZemNqtOfEq7kAfxDtGuCD3gSBYlKuUYx5MmC9/9YoaKZg="
    on_success: always
    on_failure: never
    on_start: never